epochs: 400
classWeight: 0.6
updateClip: 0.005
class_num: 60
model_name: 'stgcn'
data_path: ''
label_path: ''
num_frame_path: ''
save_path: ''
batch_size: 64
hookstatus: True
hookratio: 0.1
end_sample_num: 10000
clamp_delta: 0.01
